### ISSUE TITLE
License Restrictions?

### ISSUE THREAD

**Issue by karlredman** [dundalek/markmap#13]
Hi, I'm interested in possibility of using your code as part of a personal project. Do you have a particular license in mind for this project?

**Comment by karlredman** [comment]
Adding a note: I see that [markdown-mindmap](https://atom.io/packages/markdown-mindmap) is MIT licensed. However, the [markmap project](https://github.com/dundalek/markmap) does not indicate it's license restrictions. Sorry to be pesky. I just don't want to step on any toes.

**Comment by dundalek** [comment]
Hi, feel free to use it, MIT it is. I mentioned it in a readme now and added a license file to be more explicit.
