### ISSUE TITLE
support for utf-8 characters

### ISSUE THREAD

**Issue by schoreZ** [dundalek/markmap#17]
I am using this module to analyze structure for articles in Chinese, but the characters always extends out of the frame, like this:

![image](https://user-images.githubusercontent.com/17308957/31340854-23e59f26-accd-11e7-9988-467a5bd6b454.png)

How do I fix this?
Thanks a lot.

**Comment by dundalek** [comment]
@schoreZ I just pushed a fix (version 0.4.2). Could you please try it and close the issue if it works correctly?

**Comment by schoreZ** [comment]
Sorry for the lateness!
The problem is solved and perfect:
![image](https://user-images.githubusercontent.com/17308957/31486396-efd0d3b8-aefc-11e7-80d3-c6ea38a8e339.png)
Big hand shake :)
