### ISSUE TITLE
run the other samples ?

### ISSUE THREAD

**Issue by oceatoon** [dundalek/markmap#18]
Hi great lib !! 
I managed to see the the index.html sample 
but how do I run the other samples 
- example.parse sample ?
- txtmap ?

**Comment by dundalek** [comment]
You can use node.js from command line, do `cd examples` and then `node example.parse.js` or `node example.parse.txtmap.js`.

**Comment by oceatoon** [comment]
Thanks
you might want to put it your readme for non node devs
it works great in command line
let's say I have a variable containing md and want to build the mindmap
dynamically
 how could I integrate it into an html process like index ?
could be a nice sample for us to start from
:) thanks for your help and reactivity

**Comment by dundalek** [comment]
You can include the files from parse example in index.html and then load the file via ajax instead of fs.readFile. I think I can try to update the examples later this week.

**Comment by oceatoon** [comment]
thanks 
that would be great 
cheers

**Comment by oceatoon** [comment]
Hi :)
I'm looking for all the options of the libs view.mindmap.js 
but I can't find the source project on the web  ? :(
I'm trying to close the first or second level of the map when opening 
thanks for your help 
merry Xmas

**Comment by dundalek** [comment]
It took a while longer, but more browser examples and better instructions are now included.
