### ISSUE TITLE
Will this work in a browser-only scenario?

### ISSUE THREAD

**Issue by rmtuckerphx** [dundalek/markmap#25]
Trying to setup a simple client-side only diagram hosted on Github Pages where the data.md file is contained in the repo.

Do you have a sample of that?

**Comment by dundalek** [comment]
Yeah, there are examples of the browser usage here: https://github.com/dundalek/markmap/tree/master/examples/browser

**Comment by dundalek** [comment]
Depends on how the publishing system is set up. This library is primarily aimed for developers, so some expertise to wire things up is needed.
