### ISSUE TITLE
Hover items

### ISSUE THREAD

**Issue by DanCarterGMSL** [dundalek/markmap#27]
I've cloned the repo and done an `npm install`. When running the samples, the mind map displays correctly, but when I hover over an entry, I don't get any sort of hovering behaviour like in the example page at http://kb.knomaton.org/multi-agent-systems/. Is this the expected behaviour? If not, is it possible to add?

**Comment by dundalek** [comment]
This library is for rendering the mindmap only. Anyone can implement hover behavior to suit their needs. The tooltips you saw in the demo are implemented in https://github.com/dundalek/kmdoc

**Comment by DanCarterGMSL** [comment]
Thanks, that's really helpful!
