### ISSUE TITLE
[feature request?] appliction/extension mixes mindmap and markdown

### ISSUE THREAD

**Issue by retsyo** [dundalek/markmap#35]
In fact, while I am preparing some presentation on `NumPy`/`SciPy`, I dream of an application which mixes mindmap and markdown with the following functions

# first of all 
1.1 it can run on my local computer, for me, which is a Windows one. I am not willing to write a presentation on any smartphone/pad

1.2 it can run without needing to register a user

# The markdown side
it seems that [Sweave](http://www.statistik.lmu.de/~leisch/Sweave/) or [knitr](https://yihui.org/knitr/) for [RStudio](https://rstudio.com/) support the function in markdown side

2.1 feature is supplied by [markdown-preview-enhanced](https://atom.io/packages/markdown-preview-enhanced) or [typora](https://typora.io/)

2.1.1 markdown with at least syntax highlighting, math(for example, MathJax), flowchart

2.1.2 the title `# title` can be auto-numbered, for example

```
# title 1
## sub title 1
## sub title 2
# title 2
```
is rendered as something like
```
# 1. title 1
## 1.1 sub title 1
## 1.2 sub title 2
# 2. title 2
```
2.1.3 the markdown can be exported to pdf, docx, etc. A solution via huge Latex bundle is a bad one.

2.2 extra features

2.2.1 embed picture, pandas dataframe like [Jupyter](https://jupyter.org/) does.

2.2.2 embed programming, for me Python is used here,  output/varaibles like [codebraid](https://github.com/gpoore/codebraid) does

# the mindmap side
3.1 markdown is translated into mindmap. As a result, we can read the chapters/heading clearly while markdown's heading is rendered as the node of mindmap. Yes, [atom-markdown-mindmap](https://github.com/dundalek/atom-markdown-mindmap) does so.

3.2 math formula is supported in the node.  Well, https://github.com/dundalek/atom-markdown-mindmap/issues/35 has mentioned it.

3.3 non-heading parts between 2 sub-heading in markdown is treated as the comment of the node, like [mindmup](https://www.mindmup.com/)'s Note does.

3.4 in mindmap, we can drag the node as https://github.com/dundalek/atom-markdown-mindmap/issues/51 said. As a result, the heading and its sub-contents in markdown are re-arranged.

3.5 we can edit in both markdown and mindmap

# alike app

**Comment by dundalek** [comment]
Hi, thanks for the write up. However, I think this is a wrong place to post it. Markmap is just a component to render mindmaps which can be used as a library. So you should better ask other projects.
