### ISSUE TITLE
Not working in firefox

### ISSUE THREAD

**Issue by trond7** [dundalek/markmap#5]
Latest version is not working on firefox.
It is working fine in crome.
No js errors in console
Added a screendump that shows how it looks.

The demo at: http://kb.knomaton.org/multi-agent-systems/
Works fine in firefox.

Installed with npm on 2016-04-08

I am using Firefox SRD 38.7.0 on mac and the map is not displayed.
The same problem on my ubuntu machine (cant remember firefox version)

<img width="823" alt="screen shot 2016-04-08 at 12 49 34" src="https://cloud.githubusercontent.com/assets/6748232/14381949/5ed8e8ac-fd8a-11e5-87b4-d5bf9a2dd548.png">

**Comment by guinetn** [comment]
Hi trond7

Fix it by changing 2 lines in view.mindmap.js(129):

 // 'SVGElement.offsetWidth' is deprecated in chrome > M50
// state.height = svg.node().offsetHeight;
// state.width = svg.node().offsetWidth;    
    state.width = svg.node().getBoundingClientRect().width;
    state.height = svg.node().getBoundingClientRect().height;

**Comment by dundalek** [comment]
Fixed via https://github.com/dundalek/markmap/pull/7 published to npm as v0.3.2
